version: "3.0"
services:
  drill:
    image: mpolatcan/hstack-drill:alpine
    environment:
      - DRILL_MODE=distributed
      - DRILL_CLUSTER_ID=hstack-drill-cluster
      - DRILL_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
    ports:
      - 8047

  # -------------------------------- ZOOKEEPER QUORUM ------------------------------------------
  zk1:
    image: zookeeper
    restart: always
    container_name: zk1
    hostname: zk1
    ports:
      - 2181:2181
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

  zk2:
    image: zookeeper
    restart: always
    hostname: zk2
    container_name: zk2
    ports:
      - 2182:2181
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zk1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zk3:2888:3888

  zk3:
    image: zookeeper
    restart: always
    hostname: zk3
    container_name: zk3
    ports:
      - 2183:2181
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=0.0.0.0:2888:3888
  # -------------------------------------------------------------------------------------------
